FROM node:20.13.1-alpine as builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

# Construir la aplicación
RUN npm run dev

# Servir la aplicación con un servidor web ligero
FROM nginx:alpine

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

# Copiar configuración de nginx personalizada (opcional)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD ["npm", "run", "dev"]
# CMD ["nginx", "-g", "daemon off;"]