FROM node:20.13.1-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Copiar el resto de los archivos
COPY . .

# Instalar dependencias
RUN npm ci --only=prodyction
# RUN npm run dev

# Puerto que usa Express
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["node", "server.js"]